yaml code

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -24,6 +24,12 @@ concurrency:
   group: "pages"
   cancel-in-progress: false
 env:
+  NEXT_PUBLIC_FIREBASE_API_KEY: ${{ NEXT_PUBLIC_FIREBASE_API_KEY }}
+  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
+  NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
+  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
+  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
+  NEXT_PUBLIC_FIREBASE_APP_ID: ${{ NEXT_PUBLIC_FIREBASE_APP_ID }}
   RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
 jobs:
   # Build job
@@ -32,9 +38,33 @@ jobs:
     steps:
       - name: Secret key exists
         run: |
-          echo "Resend setup test from Bash!"
+          echo "secret keys setup test from Bash!"
           if [ -z "$RESEND_API_KEY" ]; then
-            echo "Error: Secret not found!"
+            echo "Error: RESEND_API_KEY not found!"
+            exit 1
+          fi
+          if [ -z "$NEXT_PUBLIC_FIREBASE_API_KEY" ]; then
+            echo "Error: NEXT_PUBLIC_FIREBASE_API_KEY not found!"
+            exit 1
+          fi
+          if [ -z "$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN" ]; then
+            echo "Error: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN not found!"
+            exit 1
+          fi
+          if [ -z "$NEXT_PUBLIC_FIREBASE_PROJECT_ID" ]; then
+            echo "Error: NEXT_PUBLIC_FIREBASE_PROJECT_ID not found!"
+            exit 1
+          fi
+          if [ -z "$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET" ]; then
+            echo "Error: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET not found!"
+            exit 1
+          fi
+          if [ -z "$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID" ]; then
+            echo "Error: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID not found!"
+            exit 1
+          fi
+          if [ -z "$NEXT_PUBLIC_FIREBASE_APP_ID" ]; then
+            echo "Error: NEXT_PUBLIC_FIREBASE_APP_ID not found!"
             exit 1
           fi
       - name: Checkout
